### ISSUE TITLE
Update Build_LDC_for_Android

### ISSUE THREAD

**Issue by buggins** [joakim-noah/android#5]
I would be useful to update instructions
https://wiki.dlang.org/Build_LDC_for_Android

There is no particular commit specified for ldc-developers in "Build ldc for Android/ARM" section.
So it's hard to apply patches for ldc, druntime, phobos.
If you try to use instructions straightforward (latest master branch), none of patches can be applied.
I found that ldc_android_arm patch is applicable to -beta2 tagged version.
But patches for druntime and phobos - still do not work.

Is it possible to specify **git checkout XXXX** line to get patches working?

**Comment by joakim-noah** [comment]
Yes, those instructions are somewhat out of date now.  I'm working on a beta of the Android releases, now that I've been able to run the compiler test suite also.  I thought I'd update the instructions then, but I can update them partially now too.

**Comment by buggins** [comment]
I've translated android_native_app_glue.c to .d
It would be useful to include it to your lib - to avoid using .c at all

**Comment by joakim-noah** [comment]
Well, technically there is no library, this repo is all D headers for Android's bundled C libraries, along with some D sample apps.  I have people copy over `android_native_app_glue.c` from the NDK and build it themselves, in the instructions from the wiki.

I'd like to translate most of it to D, but some of it may need to stay C in order to invoke `rt_init` and `rt_term` before any D code is called.  I have not explored what is feasible there, have you?

Have you built an app that calls the GC and used it with your translated wrapper?  I don't believe the two sample apps will really test that, as they're translated from C.

**Comment by buggins** [comment]
Sent pull request with translated android_native_app_glue

I've only built native-activity example with it. Works ok.
But I have not use any GC related code.

BTW, when I tried to use std.string.toStringz linking has been failed - no symbol found for toStringz.
Is libphobos buid complete or some truncated one?

**Comment by joakim-noah** [comment]
I responded to the PR separately.

As for toStringz, I see the symbol in the phobos library that came with the alpha2 release and there are unit tests that call it.  `readelf -sW lib/libphobos2-ldc.a | grep toStringz` will show you the symbols it has.  You can try comparing the symbol the linker is looking for with the one in phobos to see what the mismatch is.

If you can't figure it out, file an issue on the ldc repo and I'll look into it.

**Comment by joakim-noah** [comment]
Updated the wiki page to use llvm 3.8, the new ltsmaster branch, and NDK r11, will consider adding instructions for compiling natively on Android with the beta release.
