### ISSUE TITLE
LDC for Android issue

### ISSUE THREAD

**Issue by buggins** [joakim-noah/android#7]
(I understand, it's offtopic, but I don't know where to submit issue)

Source code:
static short[] DATA = [10,  10,  10,  10,  30,  30,  30,  30,  30];

DATA.length is null when accessing on Android.
Works ok if marked __gshared

Are TLS variables supported?

**Comment by joakim-noah** [comment]
Yes, that is a bug in the alpha2 release, that has since been fixed in the beta.  You can build the beta yourself by using the instructions from the wiki, or I'll have a build out in a couple weeks.

Specifically, the alpha release would sometimes not bracket TLS data properly with the `_tlsstart` symbol, which I only found after running the ldc compiler test suite recently.  That fix has been merged upstream, so if you build the latest ldc from the ltsmaster branch, you can use it.

As [I mentioned earlier, you can report ldc issues](https://github.com/joakim-noah/android/issues/5#issuecomment-211787927) at [the ldc repo](https://github.com/ldc-developers/ldc/issues).  This bug has already been fixed upstream, but you can report any other Android issues you run into there.
