### ISSUE TITLE
Missing references to functions form core.stdc.stdlib

### ISSUE THREAD

**Issue by Mergull** [joakim-noah/android#8]
When I import core.stdc.stdlib and using functions from it then:
atof - undefined reference to 'atof'
abs - undefined reference to 'abs'
strtod - ok
malloc - ok

**Comment by joakim-noah** [comment]
I didn't even know what you're talking about at first, but presumably you're talking about the compiler build.  Bugs with that should be reported at the ldc repo, not here.  Anyway, we can deal with this here for now, what compiler version are you using?  The latest 1.1.0 build has both `atof` and `abs`, so not sure why it wouldn't work.

**Comment by Mergull** [comment]
I'm using LDC2-1.1.0-beta6-android-arm. On PC on normal LDC2 it works fine.

**Comment by joakim-noah** [comment]
So you are running the native Android compiler on an Android device?  I just tried the following test code with that compiler and had no problem:
```d
import std.stdio: writefln;
import core.stdc.stdlib: abs, atof;
void main() { writefln("abs of -3 is %d and abs of -5 is %d", abs(-3), abs(-5));
writefln("atof of 3.1415 is %g and atof of -1.71513 is %g", atof("3.1415"), atof("-1.71513"));
}
```
Can you say what error it is exactly that you're getting?

**Comment by Mergull** [comment]
I'm sorry, I made a mistake. I'm using ldc2-android-arm-1.1.0-beta4-linux-x86_64.tar.xz on linux.

(.text._D5Bubel9MathParse10MathParser5parseFxAaZ5parseMFZv[_D5Bubel9MathParse10MathParser5parseFxAaZ5parseMFZv]+0x143c): undefined reference to `atof'
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by joakim-noah** [comment]
Can you paste the ldc command used to compile that D file and the linker command used to link it?

**Comment by Mergull** [comment]
DIRS - files paths

ldc -mtriple=armv7-none-linux-androideabi -I../../ -c -d-version=GLES20 -oq -odobj/Bubel $DIRS

export NDK=/home/mergul/Dokumenty/Android/android-ndk-r13
export NDK_ARCH=x86_64
export LDC=/home/mergul/Dokumenty/Android/ldc2-android-arm-1.1.0-beta4-linux-x86_64

$NDK/toolchains/llvm/prebuilt/linux-$NDK_ARCH/bin/clang -Wl,-soname,libmain_d.so \
-shared --sysroot=$NDK/platforms/android-13/arch-arm obj/Bubel/*.o \
$LDC/lib/libphobos2-ldc.a $LDC/lib/libdruntime-ldc.a \
-lgcc \
-gcc-toolchain $NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-$NDK_ARCH \
-no-canonical-prefixes -fuse-ld=bfd -target armv7-none-linux-androideabi \
-Wl,--fix-cortex-a8 -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now \
-mthumb -L$NDK/platforms/android-13/arch-arm/usr/lib -llog -landroid -lGLESv2 \
-lc -lm -L ../../derelict -lfreetype -lfreeimage -lassimp3 -lsdl2 -lutil -o jni/src/libmain_d.so

**Comment by joakim-noah** [comment]
OK, I should have looked into this closer when you opened the issue.  It turns out that [`abs` and `atof`were inline functions defined in `stdlib.h` itself in early versions of Android](https://android.googlesource.com/platform/bionic/+/android-2.3_r1/libc/include/stdlib.h#78).  That means they couldn't be linked against from D, as they could in later Android versions when they were standalone compiled functions with their own symbols.

There are so many libstdc functions in the D headers, there hasn't been an effort to check to make sure all the bionic libc versions provide all the symbols.  Maybe that needs to be checked at some point, but for now you should be able to translate the above C definitions to D yourself if you want to build for an older Android.
